"""
Django settings for NewsPaper project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
# from environ import Env
# env=Env()
# env.read_env()
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n3xu#5w(bskbnee!#x*mq^l48+r7t&p46davw)9=-j)r$@^q4a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
SITE_ID = 1


# Application definition


INSTALLED_APPS = [

     'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Blog',
    'Accounts',
    'ckeditor',
    'ckeditor_uploader',
    'django.contrib.sites',  
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
]
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # standard django backend
    'allauth.account.auth_backends.AuthenticationBackend', # all auth backend
]

MIDDLEWARE = [
    'allauth.account.middleware.AccountMiddleware',
    'Blog.middleware.MyCustomMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NewsPaper.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NewsPaper.wsgi.application'




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}




AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR, 'static']



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# SESSION_SAVE_EVERY_REQUEST = True

AUTH_USER_MODEL = 'Accounts.CustomUser'

LOGIN_REDIRECT_URL='/'
# LOGOUT_REDIRECT_URL='login'
SOCIALACCOUNT_LOGIN_ON_GET = True

#caches
# SESSION_ENGINE= 'django.contrib.sessions.backends.cache'


# SESSION_COOKIE_AGE = 3600 

CACHES = {

    'default': {

        # 'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
         "BACKEND": "django.core.cache.backends.locmem.LocMemCache",

        # 'LOCATION': '127.0.0.1:11211',

    }

}

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}


JAZZMIN_SETTINGS = {
    "site_title": "Kigali Trends",
    "site_header": "kigali",
    "site_brand": "Kigali Trends",
    "welcome_sign": "Welcome to Kigali Trends Admin",
    "site_logo": "image/undraw_online-community_3o0l.png",
    "copyright": "Engneer Gilbert",
     "custom_css": "css/custom.css",


     "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        { "app": "Blog"},
        {'app':"Accounts"},
        {"name": "Twitter", "url": "https://x.com/home?lang=en", "new_window": True},
        

     ],

    "usermenu_links": [
        {"model": "auth.user"},
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
    ],

        "apps_icons": {
        "blog":  "fas fa-cog",
    },

      "show_ui_builder": True,
    #   "show_sidebar": False,
      "navigation_expanded": True,
       "changeform_format": "verticalal_tabs",

    "custom_links": {
        "blog": [{
            "name": "Make Messages", 
            "url": "make_messages", 
            "icon": "fas fa-comments",
            "permissions": ["books.view_book"]
        }]
    },
}






